site_name: electronics notes
pages:
- [index.md, Home]
- [led.md, Leds]
- [fivefivefive.md, 555]
- [voltagereg.md, Voltage regulator]
- [atmel.md, Atmel]
- [Prototyping.md, Prototyping]
- [Sensors.md, Sensors]
- [buspirate.md, Bus Pirate]
theme: readthedocs
