site_name: electronics notes
markdown_extensions: [math]
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
pages:
- [index.md, Home]
- [soldering.md, Soldering]
- [led.md, Leds]
- [fivefivefive.md, The 555 chip]
- [voltagereg.md, Voltage regulator]
- [diode.md, Diodes]
- [transistor.md, Transistors]
- [atmel.md, Atmel]
- [oscillator.md, Oscillators]
- [Prototyping.md, Prototyping]
- [protocols.md, Protocols]
- [Sensors.md, Sensors]
- [buspirate.md, Bus Pirate]
- [cookbook.md, Cookbook]
theme: readthedocs
