site_name: electronics notes
markdown_extensions: 
 - math
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
pages:
- [index.md, Home]
- [atmel.md, Atmel]
- [buspirate.md, Bus Pirate]
- [cookbook.md, Cookbook]
- [diode.md, Diodes]
- [filters.md, Filters]
- [fivefivefive.md, The 555 chip]
- [ic.md, Integrated circuit]
- [kicad.md,KiCad]
- [laws.md, Laws]
- [led.md, Leds]
- [motors.md, Motors]
- [oscillator.md, Oscillators]
- [protocols.md, Protocols]
- [Prototyping.md, Prototyping]
- [sampling.md, Sampling]
- [Sensors.md, Sensors]
- [soldering.md, Soldering]
- [tools.md, Tools]
- [transistor.md, Transistors]
- [voltagereg.md, Voltage regulator]
theme: readthedocs
